### PR TITLE
fix links and newlines in getting started

### PR DESCRIPTION
**Pull request by RaisinTen**
I was going through the docs and noticed that the links didn't work. So, I fixed them and the newlines. :slightly_smiling_face:

### CODE REVIEW

**Comment by 4h7l** [comment]
Yes, some links don't work. I think this is because of the `slug` in the [gatsby-node.js](https://github.com/nodejs/node-addon-examples/blob/4a1e9b53a3bbd37907160ef93e41b280a3035234/website/gatsby-node.js#L25) file.

**Comment by mhdawson** [comment]
@jschlight could you take a look?

**Review by jschlight — CHANGES_REQUESTED** [review]
Thank you for reporting this issue and submitting a PR! In testing your PR, I've determined the correct form for the links is `[prerequisites](prerequisites)`, `[tools](tools)`, and `[A first project](first)`. If you make these changes and resubmit I'll be happy to look at it again. 

There is information at this link that explains how to build and test the site on your development system:

https://github.com/nodejs/node-addon-examples/blob/master/website/README.md#contributing

**Comment by RaisinTen** [comment]
Thanks for the review! Actually I can't build `gatsby` on my IA-32 linux because compiling `sharp` produces the error discussed here: https://github.com/lovell/sharp/issues/1882
I made the changes. :)

**Review by jschlight — APPROVED** [review]
LGTM with the changes.

**Review by helio-frota — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
