### PR TITLE
simplify a little Cmake config with regex

### PR DESCRIPTION
**Pull request by helio-frota**
Removes one line of CMakeLists.txt config file by using regex to run both replaces at one time.

### CODE REVIEW

**Comment by helio-frota** [comment]
@jschlight hi do you think that makes sense ? I mean it worth to remove one line and use regex (lines vs complexity thing) ?
thanks

**Review by jschlight — APPROVED** [review]
Your regex is certainly better than mine. LGTM.

**Comment by helio-frota** [comment]
@jschlight thank you for the PR review and also thank you for creating cmake example :+1:

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by jschlight** [comment]
What's cool is that this source code embedded on this page on the tutorial site has updated:

http://nodejs.github.io/node-addon-examples/build-tools/cmake-js

Now I need to update the narrative text to match.

**Comment by helio-frota** [comment]
@jschlight another cool thing is using npx with cmake-js https://github.com/helio-frota/sandwich/pull/9/commits/26db23f87e6e2acc37854acc24095bbd832ec33d#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R20 
approach provided by @NickNaso 

And we end up with 

```
npm install
npm test
```

but I like the approach you used on tutorial -- always  good to have crystal clear tutorial :+1:

**Pull request merged**
