### PR TITLE
add clang-format hook

### PR DESCRIPTION
**Pull request by gengjiawen**

### CODE REVIEW

**Comment by helio-frota** [comment]
@gengjiawen hi, question not directly related to your PR. 
I copy/past this file from node https://github.com/nodejs/node/blob/master/.clang-format 
and when I run clang-format locally it add the pointer like this:

`FILE* f` and I saw on your PR that it changes to `FILE *f`.

I can't identify the `.clang-format` file you are using, where I can get a copy to use in my personal project ?
thanks in advance

**Comment by gengjiawen** [comment]
> @gengjiawen hi, question not directly related to your PR.
> I copy/past this file from node [https://github.com/nodejs/node/blob/master/.clang-format](https://github.com/nodejs/node/blob/master/.clang-format?rgh-link-date=2020-11-26T15%3A41%3A55Z)
> and when I run clang-format locally it add the pointer like this:
> 
> `FILE* f` and I saw on your PR that it changes to `FILE *f`.
> 
> I can't identify the `.clang-format` file you are using, where I can get a copy to use in my personal project ?
> thanks in advance

It should be this rule:  `PointerAlignment`. You can verify it here: https://zed0.co.uk/clang-format-configurator/.

**Comment by helio-frota** [comment]
@gengjiawen thank you and also for sharing this config tool :+1:

**Review by mhdawson — APPROVED** [review]
LGTM

**Pull request merged**
