### PR TITLE
Added HelloWorld example as requested

### PR DESCRIPTION
**Pull request by Misery42**
See https://github.com/nodejs/node-addon-examples/issues/83#issuecomment-521363105

Reading the readme files in the repository and the first HelloWorld example didn't clarify how I should structure this example properly, so I hope you could help me do it right, in case I made a mistake.

### CODE REVIEW

**Comment by mhdawson** [comment]
I'll have to look a bit more closely but one thing about the rename is that we have use common names across the n-api node-addon-api and the other examples.  For that reason we would either need to keep the original naming and the new example in a new directory or rename the corresponding example for the other approaches as well (node-addon-api, nan, etc)

**Comment by Akito13** [comment]
@mhdawson Could you elaborate on your proposition with a precise example regarding this specific pull request? So there won't be any additional mistakes.

**Comment by mhdawson** [comment]
I'd suggest adding a new example called "string_handling" with the focus on showing how to use the string functions.  The starting point could be the hello world example, but getting/creating more strings, with each set of commands that gets/creates a string illustrating one of the points which is not clear.  For example, the different ways that you can create a string which is null terminate (using auto length, getting the length and then specifying it etc.

The output itself might just be Hello world string1, string2, string3 etc.

but the code whichs gets/creates string1, string2, etc. would be comment to illustrate and explain the gotcha/issues you ran into?

Ideally, the same example could also be implemented in plain N-API (in addition to to node-addon-api)

Does that make sense?

**Comment by mhdawson** [comment]
@theAkito are you still planning to work on this?

**Comment by mhdawson** [comment]
I'm going to close this since there has not been a response to the last questions/pings for over a year. Please let us know if that is not the right thing to do.

**Pull request closed without merging**
