### PR TITLE
added method wraps, and added v8::string for nan::new methods

### PR DESCRIPTION
**Pull request by winfinit**
updated rest of the examples

### CODE REVIEW

**Comment by rvagg** [comment]
I intentionally opted for not using `NAN_METHOD` in these and `v8::String` shouldn't be necessary

**Comment by winfinit** [comment]
@rvagg I know that v8::String is optional, however being explicit in example I think is not a bad thing. As far as NAN_METHOD, i believe that if spec is followed, and documented macros are used, you are more likely to have more portable code, which is a purpose of nan in my opinion, otherwise you are better off just writing a native module from the get go.

**Comment by rvagg** [comment]
@kkoopa @bnoordhuis could I get an opinion from you two about this? My preference is to be explicit and use full signatures now that we can:

```c++
void MyObject::GetValue(const Nan::FunctionCallbackInfo<v8::Value>& info) {
```

vs the classic shorthand which is now just an alias for the above:

```c++
NAN_METHOD(MyObject::GetValue) {
```

I'd prefer the former because it's clearer what's going on and is valid C++ while the latter is much more opaque. The benefits of the shorthand are that it's short, obviously, and that it's potentially forward-compatible with changes that we may have to make for the signature although I'd hope that we'd be able to shoehorn most of those into what we have now, at least until the V8 team decide to do a table-flip and change _everything_.

**Comment by kkoopa** [comment]
Both are valid C++. I prefer the shorter forms, as they get rid of unnecessary boilerplate, but both are equally valid.

Newer versions of V8 are moving to callback signatures with `Local<Message>` instead of `Local<String>`, to allow for `Symbol`, but that is already being mitigated, so it should not be a problem.

**Comment by bnoordhuis** [comment]
Mild preference for the first form, it's more readable and explicit.

**Comment by rvagg** [comment]
2 vs 2, we have a stale-mate so I'd leave it as it is for now.

@agnat, @TooTallNate, got any opinions on the topic that are strong enough to share?

**Comment by agnat** [comment]
I prefer the explicit version.

**Comment by mhdawson** [comment]
This is quite old, and we don't have involvement on the NAN side for the examples at this point so I'm going to close this PR. Please comment/reopen if you don't think that is the right thing to do.

**Pull request closed without merging**
