### PR TITLE
Reorganize examples into categorized folders

### PR DESCRIPTION
**Pull request by matthewkeil**
Reorganized the examples into categorized folders and updated the `test_all` script for the new directory format.

Here is the layout that was used.  Each "category" has several examples and each example can have multiple versions of native integration (nan, node-addon-api, napi): 
```sh
REPO_ROOT
├── test_all.js
├── package.json
├── README.md
└── src
    ├── 1-getting-started
    │   ├── example1
    │   │   ├── nan
    │   │   ├── node-addon-api
    │   │   └── napi
    │   ├── example2
    │   └── example3
    ├── 2-js-to-native-conversion
    ├── 3-context-awareness
    ├── 4-references-and-handle-scope
    ├── 5-async-work
    ├── 6-threadsafe-function
    ├── 7-events
    └── 8-tooling
```

The `test_all.js` file was updated to reflect the new structure and I also massaged the output a bit at the end for a bit more feedback.  The file was not originally running the `test` script in each package, it was just running `install`.  I added a bit of logic to run the `test` script found in the package.json and then output whether the install works/doesnt, if a test was found/wasnt and if the test ran successfully.  I found one that did not run successfully because the script was not setup in the package.json.  There is a file in there that looks like a "test" case but its an infinite loop.  Will fix that in a subsequent PR.

Updated `test_all.js` output (after the output that was shown before):
```sh
passed: /Users/matthewkeil/Documents/dev/chainsafe/node-addon-examples/threadsafe-function/thread_safe_function_round_trip/napi
passed: /Users/matthewkeil/Documents/dev/chainsafe/node-addon-examples/threadsafe-function/threadsafe-async-iterator/node-addon-api
passed: /Users/matthewkeil/Documents/dev/chainsafe/node-addon-examples/threadsafe-function/typed_threadsafe_function/node-addon-api
no test found:
    /Users/matthewkeil/Documents/dev/chainsafe/node-addon-examples/threadsafe-function/promise-callback-demo/node-addon-api
    /Users/matthewkeil/Documents/dev/chainsafe/node-addon-examples/threadsafe-function/thread_safe_function_counting/node-addon-api
failed install:
    /Users/matthewkeil/Documents/dev/chainsafe/node-addon-examples/general/6_object_wrap/napi
failed tests:
    /Users/matthewkeil/Documents/dev/chainsafe/node-addon-examples/threadsafe-function/thread_safe_function_with_object_wrap/node-addon-api
```

Questions for how to make this better:
1) Should the categories and examples be numbered so they show up in a pre-determined order?
2) Should the categories be placed in a `src` folder?

### CODE REVIEW

**Comment by matthewkeil** [comment]
@mhdawson @legendecas @gabrielschulhof @vmoroz got this updated per the discussion on the meeting last week

**Comment by mhdawson** [comment]
@matthewkeil  I think its starting to look good, but I think `build_with_cmake` which is still at the top level should likely be under the src/8-tooling directory?

**Review by mhdawson — APPROVED** [review]
LGTM with one suggestion/comment

**Review by legendecas — APPROVED** [review]

**Comment by matthewkeil** [comment]
Just getting back from vacation. Thanks for pushing that commit @legendecas . If that was the only thing left feel free to merge when you guys are ready @mhdawson

**Pull request merged**
