### PR TITLE
update hello_world README.md

### PR DESCRIPTION
**Pull request by ObiWahn**
Please let me know if anything needs to be changed. I am not a native speaker, but I am willing to improve and take a few iterations. If you give me some feedback I am more likely to update the rest as I explore NAN and v8.

### CODE REVIEW

**Comment by guyellis** [comment]
While you're editing this file. I think that in Step 3 this:

```
This file is written in YAML and ...
```

should be changed to:

```
This file is written in JSON and ...
```

**Comment by evan-king** [comment]
+1 at least this version compiles.

**Comment by djhogan** [comment]
+1 this fixed the hello example for me.

**Comment by mhdawson** [comment]
@ObiWahn did you mean to close this?

**Pull request closed without merging**
