### PR TITLE
doc: add boilerplate files to repo

### PR DESCRIPTION
**Pull request by mhdawson**

### CODE REVIEW

**Review by KevinEady — CHANGES_REQUESTED** [review]
See comments regarding license.

Secondly, should we also add the PR issue template https://raw.githubusercontent.com/nodejs/node-addon-api/main/.github/PULL_REQUEST_TEMPLATE.md ? It's the same contents as `CONTRIBUTING.md`, but will show the text in any new PR created.

**Comment by mhdawson** [comment]
@KevinEady good catch added .PULL_REQUEST_TEMPLATE.md and accepted suggestion to licence.

**Comment by mhdawson** [comment]
@KevinEady if you are checking GitHub could you have a re-review so I can land this one?

**Review by KevinEady — APPROVED** [review]
LGTM

**Pull request merged**
