### PR TITLE
Move code that is necessary to run out of assert()

### PR DESCRIPTION
**Pull request by twoi**
so it runs in non-debug builds

### CODE REVIEW

**Comment by twoi** [comment]
@mhdawson Haven't come across this anywhere else, but haven't surveyed gabrielschulhof's code either...

**Comment by gabrielschulhof** [comment]
@twoi would you mind rebasing the PR so that it'll run through the CI?

**Comment by gengjiawen** [comment]
@twoi This need rebase.

**Comment by mhdawson** [comment]
@twoi ping

**Comment by mhdawson** [comment]
It's been close to a year without a response to the last pings on the issue. I'm going to close. Please let us know if that was not the right thing to do.

**Pull request closed without merging**
