### PR TITLE
example: add TypedThreadSafeFunction

### PR DESCRIPTION
**Pull request by KevinEady**
This adds the TypedThreadSafeFunction example from the [documentation](https://github.com/nodejs/node-addon-api/blob/main/doc/typed_threadsafe_function.md).

### CODE REVIEW

**Comment by KevinEady** [comment]
This replicates the gcc-11 problem with c++20 listed at https://github.com/nodejs/node-addon-api/issues/1007

**Review by mhdawson — APPROVED** [review]
LGTM

**Comment by KevinEady** [comment]
Hi @mhdawson and team,

This is ready for review

**Review by legendecas — APPROVED** [review]

**Review by mhdawson — APPROVED** [review]
LGTM again :)

**Pull request merged**
