### PR TITLE
Add CMake.js support and use NAN shorthands

### PR DESCRIPTION
**Pull request by maddouri**
Hi,

I'm currently learning how to interface C++ code with Node.js (and later with Electron) and I found the examples very helpful :)

Since NAN and CMake made my task easier, I would like to suggest the following:
- Copy `*/nan` examples to `*/nan_cmake-js`
- Use [CMake.js](https://www.npmjs.com/package/cmake-js) instead of `gyp`
- Use NAN's shorthands (e.g. `NAN_METHOD()`) over full signatures
- Minor updates to the JavaScript code

Thanks

### CODE REVIEW

**Comment by rvagg** [comment]
Since node-gyp remains the recommended way to build native addons I don't think this belongs here. Perhaps it's something you could contribute to the cmake.js project?

**Comment by maddouri** [comment]
I see.

I'll keep updating my fork with nan/cmake stuff nonetheless. Coming from a C++ background, this solution seems to integrate well within my usual workflow and tools.

Thanks anyway for taking the time to review my pull request :)

**Comment by eljefedelrodeodeljefe** [comment]
Knowing `Cmake.js`, b/c of general interop problems with Cmake and Cmake being a dependency that needs to be installed properly (which we want to avoid in the feature, afaics) I'd vote for closing this. The examples are nice though and could be referenced to from outside or you run a repo yourself.

**Comment by eljefedelrodeodeljefe** [comment]
Thank for the contribution @maddouri, but I don't think this will go forward. If someone objects or Cmaks.js gains adoption, we could revisit this.

**Pull request closed without merging**
